---
- hosts: localhost
  connection: local
  roles:
    - { role: vpc, tags: [ 'vpc', 'infra', 'always' ] }
    - { role: app-ec2, tags: [ 'app-ec2', 'infra' ] }
    - { role: rds, tags: [ 'rds', 'infra' ] }
